/**
 * This files is auto-generated by VenomVendor on Thu May 05 2016 02:35:43 GMT+0530 (IST)
 */
class Hash {
    static short() {
        return this.long().substr(0, 7);
    }

    static long() {
        return 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
    }

}
export default Hash;
